spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/artemaverkov
    username: artemaverkov
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
cache:
  max-size: 5
  algorithm: LRU
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
server:
  port: 8088
---
spring:
  cloud:
    compatibility-verifier:
      enabled: false
