server:
  port: 8088
USER_MANAGER_URL: http://localhost:8084/users
spring:
  application:
    name: news-api
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8086




