= Система управления новостями

Данный документ предоставляет описание проекта "Система управления новостями" и его интерфейсов.

== Стэк
Использование Spring Boot 3.x, Java 17, Gradle, PostgreSQL, Spring Security, Spring Cloud Config, WireMock, Docker,
    spring-cloud-feign-client, testcontainers

== Структура проекта

Проект имеет следующую структуру:

- `src`: Исходный код проекта
- `docs`: Документация
- `docker`: Файлы Docker для контейнеризации приложения и базы данных

== Запуск проекта

Для запуска проекта выполните следующие шаги:

1. Склонируйте репозиторий с проектом:

[source,bash]
----
$ git clone https://github.com/ArtsemAverkov/NewsManager.git
----

2. Перейдите в директорию проекта:

[source,bash]
----
$ cd project
----

3. Соберите проект с помощью Gradle:

[source,bash]
----
$ gradle build
----

4. Запустите проект с помощью Docker Compose:

[source,bash]
----
$ docker-compose up
----

5. Проверьте работу проекта, открыв веб-браузер и перейдя по адресу `http://localhost:8088/news`.

== Использование

После установки вы можете использовать проект для следующих целей:

- Просмотр всех новостей по адресу http://localhost:8088/news
- Если вы хотите посмотреть новость с ее коментариями То введите адрес `http://localhost:8088/news/{id}` где di это
номер новости однако вас попрося войти если вы зарегистрированы то введите свое ИМЯ и ПАРОЛЬ если нет то зарегистрируйтесь
по POST запросу по адресу  http://localhost:8088/users/create отправьте запросс в виде Json пример:
{
  "username": "test",
  "password": "test",
  "role": "SUBSCRIBER"
}
где role это роль с которой вы регистрируетесь, для вас доступно 2 роли SUBSCRIBER с этой ролью вы можете
просматривать новости, коментарии а также оставлять коментарии и удалять только свои коментарии,
роль JOURNALIST дает возможность что и SUBSCRIBER и добовлять и удалять только свои новости.

- Добавление Новостей осуществляеться по POST запросу по адресу  http://localhost:8088/news
отправьте запросс в виде Json пример:
{
 "title":" Same Title",
 "text":" Same Text"
}

- Удаление новости производиться DELETE (обратите внимание если вы не являетесь автором новости вы
не сможете ее удалить) запросом по адресу http://localhost:8088/news/{id}
где Id это id новости которую вы оставили.
- Также есть обновления новости производиться по PATCH запросу по адресу http://localhost:8088/news/{id}
где Id это id новости которую вы оставили а также отправить этот запрос с Json например:
вы отправляете http://localhost:8088/news/1
и Json
{
 "title":" Same Title",
 "text":" Same Text"
}
- есть поиск новостей по содержанию или дате вы должны отправить GET запрос
 по адресу http://localhost:8088/news/search?data=2023-06-30 либо http://localhost:8088/news/search?query=sameText
будет выдан результат в виде списка новостей

- Добавление Коментария осуществляеться по POST запросу по адресу  http://localhost:8088/comment
отправьте запросс в виде Json пример:
{
 "newsId": 1,
 "text":" Same Text"
}
где newsId это id новости в которой вы хотите оставить коментарий.

- Удаление коментария производиться DELETE запросом по адресу http://localhost:8088/comment/{id}
где Id это id коментария который вы оставили.
- Также есть обновления коментария производиться по PATCH запросу по адресу http://localhost:8088/comment/{id}
где Id это id коментария который вы оставили а также отправить этот запрос с Json например:
вы отправляете http://localhost:8088/comment/1
и Json
{
 "text":" Same Text"
}
- есть поиск коментарие по содержанию или дате вы должны отправить GET запрос
 по адресу http://localhost:8088/comment/search?data=2023-06-30 либо http://localhost:8088/comment/search?query=sameText
будет выдан результат в виде коментрариев и новостей к которым они относяться.
== Заключение

Дополнительные вопросы или замечания можно отправить по адресу `https://www.linkedin.com/in/артем-аверков-aa7663239/`.

Спасибо за внимание!
