version: '3.8'
services:
  newsManager:
    build:
      context: services/newsManager
      dockerfile: Dockerfile
    image: 'applicatio15:news'
    environment:
      - SPRING_APPLICATION_NAME=news-api
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CONFIG_IMPORT=optional:configserver:http://settingApiManager:8086
      - SPRING_REDIS_HOST=http://redisCache
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/root
      - USER_MANAGER_URL=http://userManager:8084/users
    ports:
      - 8088:8088
    depends_on:
      - userManager
      - settingApiManager
      - redisCache

  userManager:
    build:
      context: services/userManager
      dockerfile: Dockerfile
    environment:
      - SPRING_APPLICATION_NAME=user-api
      - SPRING_CONFIG_IMPORT=optional:configserver:http://settingApiManager:8086
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/root
    image: 'applicatio15:user'
    ports:
      - 8084:8084
    depends_on:
      - settingApiManager

  settingApiManager:
    build:
      context: services/settingApiManager
      dockerfile: Dockerfile
    image: 'applicatio15:setting'
    ports:
      - 8086:8086

  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=artemaverkov
      - POSTGRES_DB=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432

  redisCache:
    image: 'redis'
    ports:
      - 6379:6379






